// Trackable Member App routes, derived from the <Routes> in src/App.jsx.
// Dynamic routes are stored as templates (":param"), never as concrete IDs.
// Pre-login auth screens (/login, /vip-login, /otp-verification,
// /special-otp-verification) are excluded: no member identity exists there.

export const PAGE_TRACKING_PLATFORM = 'setu_member_app';
export const PAGE_TRACKING_MANIFEST_VERSION = '1';

export const PAGE_TRACKING_MANIFEST = [
  { route: '/', name: 'Home', module: 'Home' },
  { route: '/profile', name: 'Profile', module: 'Profile' },
  { route: '/my-family', name: 'My Family', module: 'Profile' },
  { route: '/other-memberships', name: 'Other Memberships', module: 'Profile' },
  { route: '/nomination-details', name: 'Nomination Details', module: 'Profile' },
  { route: '/trust-id-card', name: 'Trust ID Card', module: 'Profile' },
  { route: '/add-community', name: 'Add Community', module: 'Community' },
  { route: '/user-panel', name: 'User Panel', module: 'User Panel' },
  { route: '/directory', name: 'Directory', module: 'Directory' },
  { route: '/healthcare-trustee-directory', name: 'Healthcare Trustee Directory', module: 'Directory' },
  { route: '/executive-body', name: 'Executive Body', module: 'Executive Body' },
  { route: '/executive_members_details', name: 'Executive Member Details', module: 'Executive Body' },
  { route: '/committee-members', name: 'Committee Members', module: 'Executive Body' },
  { route: '/admin-profiles', name: 'Admin Profiles', module: 'Executive Body' },
  { route: '/appointment', name: 'Appointments', module: 'Appointments' },
  { route: '/reports', name: 'Reports', module: 'Reports' },
  { route: '/reference', name: 'Reference', module: 'Reference' },
  { route: '/notices', name: 'Notices', module: 'Notices' },
  { route: '/notices/:noticeId', name: 'Notice Detail', module: 'Notices' },
  { route: '/facilities', name: 'Facilities', module: 'Facilities' },
  { route: '/facilities/:facilityId', name: 'Facility Detail', module: 'Facilities' },
  { route: '/events', name: 'Events', module: 'Events' },
  { route: '/events/:eventId', name: 'Event Detail', module: 'Events' },
  { route: '/achievements', name: 'Achievements', module: 'Achievements' },
  { route: '/achievements/:achievementId', name: 'Achievement Detail', module: 'Achievements' },
  { route: '/gallery', name: 'Gallery', module: 'Gallery' },
  { route: '/donation', name: 'Donation', module: 'Donation' },
  { route: '/donation-form', name: 'Donation Form', module: 'Donation' },
  { route: '/categories-products', name: 'Categories & Products', module: 'Shop' },
  { route: '/categoriesproducts', name: 'Categories & Products (Alias)', module: 'Shop' },
  { route: '/categories-products/list/:categoryId', name: 'Product List', module: 'Shop' },
  { route: '/categories-products/list/:categoryId/detail/:productId', name: 'Product Detail', module: 'Shop' },
  { route: '/wishlist', name: 'Wishlist', module: 'Shop' },
  { route: '/cart', name: 'Cart', module: 'Shop' },
  { route: '/create-order', name: 'Create Order', module: 'Shop' },
  { route: '/order-history', name: 'Order History', module: 'Shop' },
  { route: '/notifications', name: 'Notifications', module: 'Notifications' },
  { route: '/sponsors', name: 'Sponsors', module: 'Sponsors' },
  { route: '/sponsor-details', name: 'Sponsor Details', module: 'Sponsors' },
  { route: '/contact-us', name: 'Contact Us', module: 'Support' },
  { route: '/developers', name: 'Developer Details', module: 'Support' },
  { route: '/terms-and-conditions', name: 'Terms and Conditions', module: 'Legal' },
  { route: '/privacy-policy', name: 'Privacy Policy', module: 'Legal' },
  { route: '/app/:appSlug', name: 'Tenant Landing', module: 'Community' },
];
